### ISSUE TITLE
Is there a working instance of patternImporter()?

### ISSUE THREAD

**Issue by e2tha-e** [pattern-library/pattern-library-utilities#11]
@scottnath I'm writing a more detailed test for it and it fails at line 18 of `lib/pattern-importer.js`. The params for the through.obj param function are `(file, encoding, cb)`. However, since this is a through2 stream, the `file` param gets sent as a stream (or chunks) of data. The patternImporter() function, however, seems to want the `file` param to be a Vinyl File object, not a stream or chunks. Do you have a correct way of implementing this?

**Comment by scottnath** [comment]
Morning @e2tha-e 

Yes, the patternImporter is used by the gulp-task patterns-import, which is here:
https://github.com/pattern-library/pattern-library-utilities/blob/master/lib/gulp-tasks/patterns-import.js
specifically called here:
https://github.com/pattern-library/pattern-library-utilities/blob/master/lib/gulp-tasks/patterns-import.js#L62

```
exports.gulpImportPatterns = function (gulp, projectOptions) {
  'use strict';
  var options = utility.getOptions(getDefaultOptions(), projectOptions);

  /* the gulp task */
  gulp.task(options.taskName, options.dependencies, function () {

    return gulp.src(options.src)
      .pipe(utility.patternImporter(options.config))
      .pipe(gulp.dest('./'));

  });

};
```

You can see an instance of this being called in the gulpfile part of [this pull request](https://github.com/pattern-library/generator-pattern-library/pull/1) here:
https://github.com/scottnath/generator-pattern-library/blob/master/generators/app/templates/_gulpfile.js#L78
and here:
https://github.com/scottnath/generator-pattern-library/blob/master/generators/app/templates/_gulpfile.js#L84
```
patternUtils.gulpImportPatterns(gulp, configuration.gulpTasks.patternImporter.localPatterns);
```

as for implementing, [this example line in main.js](https://github.com/pattern-library/pattern-library-utilities/blob/master/test/main.js#L85) create a vinyl file.
```
var file = utils.createFile(createTestFilePath('test-elm-h1/pattern.yml'), 'test/', 'test/fixtures', 'just some content');
```
That is calling [create-file.js](https://github.com/pattern-library/pattern-library-utilities/blob/master/lib/create-file.js)

Does that help?

**Comment by scottnath** [comment]
@e2tha-e did you need more information on this?

**Comment by e2tha-e** [comment]
@scottnath
cc: @conortm @ericduran @sergesemashko 
I found a way to fire off `patternImporter()` in generator-pattern-library by running `gulp patterns-import-npm-base`. I then put these debug statements in `patternImporter()`:

```
module.exports = function patternImporter (options) {

  options = utils.getOptions(options);
  
  var stream = through.obj(function (file, encoding, cb) {
  
    if (file.isNull()) {
      return cb();
    }
    if (file.isStream()) {
      this.emit('error', new PluginError(PLUGIN_NAME, 'Streams not supported'));
      return cb();
    }

    // get path details for our pattern
    var paths = plUtils.getFilePaths(file);

    var patternFiles = getPatternImportData(paths, options);

    // send our pattern's files to be copied or written
    utils.writeCopyFiles(patternFiles);

var util = require('util');
console.log(typeof this);
console.log(util.inspect(this, false, null));
    this.push(file);
console.log(util.inspect(this, false, null));
    cb();
  });

  return stream;

}
```

`typeof this` is object. Why are you using the `Array.prototype.push()` method on an object? Nothing ends up added to the `this` object.

**Comment by scottnath** [comment]
@e2tha-e I copied the way this is done directly from through2:
https://github.com/rvagg/through2

**Comment by e2tha-e** [comment]
@scottnath
cc: @conortm @ericduran @sergesemashko
If you're looking at the examples using `fs.createReadStream`, I'm pretty sure that pipes an array between endpoints. It needs to push the chunk read by `fs.createReadStream` onto the array in order for `fs.createWriteStream` to have something to write.

Is there documentation on using Through2 with Vinyl File objects and Gulp as the stream opener?

**Comment by scottnath** [comment]
@e2tha-e I'm sure there is, but I can't recall where that was. 

Is your goal of digging into this to unit test it? It seems like this might be taking up a lot of time - is it possible to put that on the back burner? I feel the unit test for this can wait as there is plenty of new items to get working and this file is working.

**Comment by e2tha-e** [comment]
@scottnath Ok. Moving on to other things then

**Comment by scottnath** [comment]
@e2tha-e cool, thank you. Should I close this issue?

**Comment by e2tha-e** [comment]
@scottnath Sure. Close it.
